package model;

public enum ECompartment {
	SQUARE, 
	OVAL, 
	SQUARE_CLOSEUP_NORTH,
	SQUARE_CLOSEUP_NORTHWEST,
	SQUARE_CLOSEUP_NORTHEAST,
	SQUARE_CLOSEUP_WEST,
	SQUARE_CLOSEUP_EAST,
	SQUARE_CLOSEUP_SOUTH, SQUARE_CLOSEUP_SOUTHEAST, SQUARE_CLOSEUP_SOUTHWEST,
	DEFAULT_COMPARTMENT
}
